/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerpartsstoremanagement;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.*;
import javax.swing.*;

public class formNhanVien extends JFrame {

    /**
     * Creates new form formNhanVien
     */
    public formNhanVien() {
        initComponents();
        initTable();
    }

    public ArrayList<Staff> staffList(){
        ArrayList<Staff> staffsList = new ArrayList<>();
        try {
            String url = ConnectionString.getUrl();
            Connection connection = DriverManager.getConnection(url);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM NhanVien");

            while(resultSet.next()){
                Staff staff = new Staff(resultSet.getString("maNV"), resultSet.getString("tenNV"), 
                        resultSet.getInt("doanhThu"));
                staffsList.add(staff);
            }
        }
        catch(Exception sqlex){
            sqlex.printStackTrace();
        }        
        return staffsList;
    }
    
    public void initTable(){
        ArrayList<Staff> list = staffList();
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        Object[] row = new Object[3];
        for(int i = 0; i < list.size(); i++){
            row[0] = list.get(i).getMaNV();
            row[1] = list.get(i).getTenNV();
            row[2] = list.get(i).getDoanhThu();
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new JPanel();
        lblMaNV = new JLabel();
        lblTenNV = new JLabel();
        lblDoanhSo = new JLabel();
        txtMaNV = new JTextField();
        txtTenNV = new JTextField();
        txtDoanhSo = new JTextField();
        btnOKAdd = new JButton();
        btnOKEdit = new JButton();
        btnOKDelete = new JButton();
        btnAdd = new JButton();
        btnEdit = new JButton();
        btnDelete = new JButton();
        ScrollPane1 = new JScrollPane();
        table = new JTable();
        lblTimKiem = new JLabel();
        txtTimKiem = new JTextField();
        btnSearch = new JButton();
        btnClear = new JButton();
        jMenuBar1 = new JMenuBar();
        system = new JMenu();
        back = new JMenuItem();
        about = new JMenuItem();
        exit = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhân Viên");

        panel.setEnabled(false);

        lblMaNV.setText("Mã Nhân Viên:");
        lblMaNV.setEnabled(false);

        lblTenNV.setText("Tên Nhân Viên:");
        lblTenNV.setEnabled(false);

        lblDoanhSo.setText("Doanh Số:");
        lblDoanhSo.setEnabled(false);

        txtMaNV.setHorizontalAlignment(JTextField.CENTER);
        txtMaNV.setEnabled(false);

        txtTenNV.setHorizontalAlignment(JTextField.CENTER);
        txtTenNV.setEnabled(false);

        txtDoanhSo.setEditable(false);
        txtDoanhSo.setHorizontalAlignment(JTextField.CENTER);
        txtDoanhSo.setText("0");
        txtDoanhSo.setEnabled(false);

        btnOKAdd.setText("OK");
        btnOKAdd.setEnabled(false);
        btnOKAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKAddActionPerformed(evt);
            }
        });

        btnOKEdit.setText("OK");
        btnOKEdit.setEnabled(false);
        btnOKEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKEditActionPerformed(evt);
            }
        });

        btnOKDelete.setText("OK");
        btnOKDelete.setEnabled(false);
        btnOKDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKDeleteActionPerformed(evt);
            }
        });

        GroupLayout panelLayout = new GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMaNV, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenNV, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDoanhSo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNV)
                    .addComponent(txtTenNV)
                    .addComponent(txtDoanhSo)))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOKAdd, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOKEdit, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOKDelete, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV)
                    .addComponent(txtMaNV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNV)
                    .addComponent(txtTenNV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoanhSo)
                    .addComponent(txtDoanhSo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOKDelete)
                    .addComponent(btnOKEdit)
                    .addComponent(btnOKAdd))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        table.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Doanh Thu"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        ScrollPane1.setViewportView(table);

        lblTimKiem.setText("Tìm Kiếm:");

        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setText("Xóa Tìm Kiếm");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        system.setText("Hệ Thống");

        back.setText("Trở Về");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        system.add(back);

        about.setText("Phiên Bản");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        system.add(about);

        exit.setText("Đóng Ứng Dụng");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        system.add(exit);

        jMenuBar1.add(system);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTimKiem, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnClear)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTimKiem)
                                        .addGap(18, 18, 18))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(ScrollPane1, GroupLayout.PREFERRED_SIZE, 479, GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane1, GroupLayout.PREFERRED_SIZE, 373, GroupLayout.PREFERRED_SIZE)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTimKiem)
                            .addComponent(txtTimKiem, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch)
                            .addComponent(btnClear))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnEdit)
                            .addComponent(btnDelete))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKAddActionPerformed
        try {
            String url = ConnectionString.getUrl();
            Connection connection = DriverManager.getConnection(url);
            String query = "INSERT INTO NhanVien (maNV,tenNV,doanhThu) VALUES(?,?,?)";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, txtMaNV.getText());
            pst.setString(2, txtTenNV.getText());
            pst.setInt(3, Integer.parseInt(txtDoanhSo.getText()));
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            initTable();
            JOptionPane.showMessageDialog(null, "Thêm nhân viên thành công!");
        }
        catch(Exception sqlex){
            JOptionPane.showMessageDialog(null, sqlex);
        }

        panel.setEnabled(true);
        lblMaNV.setEnabled(false);
        lblTenNV.setEnabled(false);
        lblDoanhSo.setEnabled(false);
        txtMaNV.setEnabled(false);
        txtMaNV.setText("");
        txtTenNV.setEnabled(false);
        txtTenNV.setText("");
        txtDoanhSo.setEnabled(false);
        txtDoanhSo.setText("0");
        btnOKAdd.setEnabled(false);
        btnOKEdit.setEnabled(false);
        btnOKDelete.setEnabled(false);
    }//GEN-LAST:event_btnOKAddActionPerformed

    private void btnOKEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKEditActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = ConnectionString.getUrl();
            Connection connection = DriverManager.getConnection(url);
            String query = "UPDATE NhanVien SET tenNV=? WHERE maNV=?";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, txtTenNV.getText());
            pst.setString(2, txtMaNV.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            initTable();
            JOptionPane.showMessageDialog(null, "Sửa thông tin nhân viên thành công!");
        }
        catch(Exception sqlex){
            JOptionPane.showMessageDialog(null, sqlex);
        }

        panel.setEnabled(true);
        lblMaNV.setEnabled(false);
        lblTenNV.setEnabled(false);
        lblDoanhSo.setEnabled(false);
        txtMaNV.setEnabled(false);
        txtMaNV.setText("");
        txtTenNV.setEnabled(false);
        txtTenNV.setText("");
        txtDoanhSo.setEnabled(false);
        txtDoanhSo.setText("0");
        btnOKAdd.setEnabled(false);
        btnOKEdit.setEnabled(false);
        btnOKDelete.setEnabled(false);
    }//GEN-LAST:event_btnOKEditActionPerformed

    private void btnOKDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKDeleteActionPerformed
        try {
            String url = ConnectionString.getUrl();
            Connection connection = DriverManager.getConnection(url);
            String query = "DELETE FROM NhanVien WHERE maNV=?";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, txtMaNV.getText());
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);
            initTable();
            JOptionPane.showMessageDialog(null, "Xóa nhân viên thành công!");
        }
        catch(Exception sqlex){
            JOptionPane.showMessageDialog(null, sqlex);
        }

        panel.setEnabled(true);
        lblMaNV.setEnabled(false);
        lblTenNV.setEnabled(false);
        lblDoanhSo.setEnabled(false);
        txtMaNV.setEnabled(false);
        txtMaNV.setText("");
        txtTenNV.setEnabled(false);
        txtTenNV.setText("");
        txtDoanhSo.setEnabled(false);
        txtDoanhSo.setText("0");
        btnOKAdd.setEnabled(false);
        btnOKEdit.setEnabled(false);
        btnOKDelete.setEnabled(false);
    }//GEN-LAST:event_btnOKDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        panel.setEnabled(true);
        lblMaNV.setEnabled(true);
        lblTenNV.setEnabled(true);
        lblDoanhSo.setEnabled(true);
        txtMaNV.setEnabled(true);
        txtTenNV.setEnabled(true);
        btnOKAdd.setEnabled(true);
        btnOKEdit.setEnabled(false);
        btnOKDelete.setEnabled(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        panel.setEnabled(true);
        lblMaNV.setEnabled(true);
        lblTenNV.setEnabled(true);
        lblDoanhSo.setEnabled(true);
        txtMaNV.setEnabled(true);
        txtTenNV.setEnabled(true);
        btnOKAdd.setEnabled(false);
        btnOKEdit.setEnabled(true);
        btnOKDelete.setEnabled(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        panel.setEnabled(true);
        lblMaNV.setEnabled(true);
        lblTenNV.setEnabled(false);
        lblDoanhSo.setEnabled(false);
        txtMaNV.setEnabled(true);
        txtTenNV.setEnabled(false);
        txtDoanhSo.setEnabled(false);
        btnOKAdd.setEnabled(false);
        btnOKEdit.setEnabled(false);
        btnOKDelete.setEnabled(true);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i = table.getSelectedRow();
        TableModel model = table.getModel();
        txtMaNV.setText(model.getValueAt(i,0).toString());
        txtTenNV.setText(model.getValueAt(i,1).toString());
        txtDoanhSo.setText(model.getValueAt(i,2).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        table.setAutoCreateRowSorter(true);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(table.getModel());
        table.setRowSorter(sorter);
        String text = txtTimKiem.getText();
        if(text.length()==0){
            sorter.setRowFilter(null);
        }
        else {
            sorter.setRowFilter(RowFilter.regexFilter(text));
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        table.setAutoCreateRowSorter(true);
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(table.getModel());
        table.setRowSorter(sorter);
        txtTimKiem.setText("");
        sorter.setRowFilter(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        formMain main = new formMain();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        JOptionPane.showMessageDialog(null, "Phiên bản 1.0.0.0");
    }//GEN-LAST:event_aboutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane ScrollPane1;
    private JMenuItem about;
    private JMenuItem back;
    private JButton btnAdd;
    private JButton btnClear;
    private JButton btnDelete;
    private JButton btnEdit;
    private JButton btnOKAdd;
    private JButton btnOKDelete;
    private JButton btnOKEdit;
    private JButton btnSearch;
    private JMenuItem exit;
    private JMenuBar jMenuBar1;
    private JLabel lblDoanhSo;
    private JLabel lblMaNV;
    private JLabel lblTenNV;
    private JLabel lblTimKiem;
    private JPanel panel;
    private JMenu system;
    private JTable table;
    private JTextField txtDoanhSo;
    private JTextField txtMaNV;
    private JTextField txtTenNV;
    private JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
