/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerpartsstoremanagement;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author hamvu
 */
public class formLogIn extends javax.swing.JFrame {

    /**
     * Creates new form formLogIn
     */
    public formLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogIn = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblUserPassword = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnForgot = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        system = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");

        lblLogIn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        lblLogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogIn.setText("ĐĂNG NHẬP");
        lblLogIn.setToolTipText("");
        lblLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblUserID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserID.setText("Tên Đăng Nhập:");

        lblUserPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserPassword.setText("Mật Khẩu:");

        txtUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserIDKeyPressed(evt);
            }
        });

        txtUserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserPasswordKeyPressed(evt);
            }
        });

        btnLogIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogIn.setText("Đăng Nhập");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnNew.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNew.setText("Đăng Ký");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnForgot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnForgot.setText("Quên Mật Khẩu");
        btnForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotActionPerformed(evt);
            }
        });

        system.setText("Hệ Thống");

        about.setText("Phiên Bản");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        system.add(about);

        exit.setText("Đóng Ứng Dụng");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        system.add(exit);

        jMenuBar1.add(system);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUserID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserID)
                            .addComponent(txtUserPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnForgot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNew)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn)
                    .addComponent(btnNew)
                    .addComponent(btnForgot))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        if(txtUserID.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Yêu cầu nhập tên đăng nhập");
        }
        else {
            try{
                String url = "jdbc:sqlserver://localhost;databaseName=DBQLCH;integratedSecurity=true;";
                Connection cnn = DriverManager.getConnection(url);
                String sql = "SELECT * FROM DangNhap WHERE userid = ? and userpassword = ?";
                PreparedStatement pst = cnn.prepareStatement(sql);
                pst.setString(1, txtUserID.getText());
                pst.setString(2, txtUserPassword.getText());
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Đăng nhập thành công!");               
                    formMain main = new formMain();
                    main.setVisible(true);
                    this.setVisible(false);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Đăng nhập thất bại!");
                    txtUserID.setText("");
                    txtUserPassword.setText("");
                }
            cnn.close();
            }
            catch(SQLException sqlex){
                JOptionPane.showMessageDialog(null, sqlex);
            }
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        JOptionPane.showMessageDialog(null, "Phiên Bản 1.0.0.0");
    }//GEN-LAST:event_aboutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void btnForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotActionPerformed
        formResetPassword reset = new formResetPassword();
        reset.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnForgotActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        if(txtUserID.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Yêu cầu nhập tên đăng nhập");
        }
        else {
            try{
                String url = "jdbc:sqlserver://localhost;databaseName=DBQLCH;integratedSecurity=true;";
                Connection cnn = DriverManager.getConnection(url);
                String sql = "INSERT INTO [dbo].[DangNhap] ([userid],[userpassword]) VALUES(?,?)";
                PreparedStatement pst = cnn.prepareStatement(sql);
                pst.setString(1, txtUserID.getText());
                pst.setString(2, txtUserPassword.getText());
            
                pst.executeUpdate();           
                JOptionPane.showMessageDialog(null, "Đăng ký tài khoản thành công!");                        
                cnn.close();
            }
            catch(SQLException sqlex){
                JOptionPane.showMessageDialog(null, sqlex);
            }
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void txtUserPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserPasswordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtUserID.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Yêu cầu nhập tên đăng nhập");
            }
            else if(txtUserPassword.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Yêu cầu nhập mật khẩu");
            }
            else {
                try{
                    String url = "jdbc:sqlserver://localhost;databaseName=DBQLCH;integratedSecurity=true;";
                    Connection cnn = DriverManager.getConnection(url);
                    String sql = "SELECT * FROM DangNhap WHERE userid = ? and userpassword = ?";
                    PreparedStatement pst = cnn.prepareStatement(sql);
                    pst.setString(1, txtUserID.getText());
                    pst.setString(2, txtUserPassword.getText());
                    ResultSet rs = pst.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null, "Đăng nhập thành công!");               
                        formMain main = new formMain();
                        main.setVisible(true);
                        this.setVisible(false);
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Đăng nhập thất bại!");
                        txtUserID.setText("");
                        txtUserPassword.setText("");
                    }
                cnn.close();
                }
                catch(SQLException sqlex){
                    JOptionPane.showMessageDialog(null, sqlex);
                }
            }
        }
    }//GEN-LAST:event_txtUserPasswordKeyPressed

    private void txtUserIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtUserID.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Yêu cầu nhập tên đăng nhập");
            }
            else if(txtUserPassword.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Yêu cầu nhập mật khẩu");
            }
            else {
                try{
                    String url = "jdbc:sqlserver://localhost;databaseName=DBQLCH;integratedSecurity=true;";
                    Connection cnn = DriverManager.getConnection(url);
                    String sql = "SELECT * FROM DangNhap WHERE userid = ? and userpassword = ?";
                    PreparedStatement pst = cnn.prepareStatement(sql);
                    pst.setString(1, txtUserID.getText());
                    pst.setString(2, txtUserPassword.getText());
                    ResultSet rs = pst.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null, "Đăng nhập thành công!");               
                        formMain main = new formMain();
                        main.setVisible(true);
                        this.setVisible(false);
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Đăng nhập thất bại!");
                        txtUserID.setText("");
                        txtUserPassword.setText("");
                    }
                cnn.close();
                }
                catch(SQLException sqlex){
                    JOptionPane.showMessageDialog(null, sqlex);
                }
            }
        }
    }//GEN-LAST:event_txtUserIDKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JButton btnForgot;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnNew;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserPassword;
    private javax.swing.JMenu system;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
