/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerpartsstoremanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author hamvu
 */
public class formMain extends javax.swing.JFrame {

    /**
     * Creates new form formMain
     */
    public formMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        system = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        logOut = new javax.swing.JMenuItem();
        function = new javax.swing.JMenu();
        product = new javax.swing.JMenuItem();
        createBill = new javax.swing.JMenuItem();
        search = new javax.swing.JMenu();
        customer = new javax.swing.JMenuItem();
        searchBill = new javax.swing.JMenuItem();
        store = new javax.swing.JMenu();
        revenue = new javax.swing.JMenuItem();
        staff = new javax.swing.JMenuItem();
        statistic = new javax.swing.JMenu();
        detail = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Cửa Hàng Bán Linh Kiện Máy Tính");

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computerpartsstoremanagement/UIT.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        system.setText("Hệ Thống");

        about.setText("Phiên Bản");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        system.add(about);

        exit.setText("Đóng Ứng Dụng");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        system.add(exit);

        logOut.setText("Thoát Đăng Nhập");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        system.add(logOut);

        jMenuBar1.add(system);

        function.setText("Chức Năng");

        product.setText("Sản Phẩm");
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        function.add(product);

        createBill.setText("Lập Hóa Đơn");
        createBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBillActionPerformed(evt);
            }
        });
        function.add(createBill);

        jMenuBar1.add(function);

        search.setText("Tra Cứu");

        customer.setText("Khách Hàng");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        search.add(customer);

        searchBill.setText("Hóa Đơn");
        searchBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBillActionPerformed(evt);
            }
        });
        search.add(searchBill);

        jMenuBar1.add(search);

        store.setText("Cửa Hàng");

        revenue.setText("Doanh Thu Cửa Hàng");
        revenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueActionPerformed(evt);
            }
        });
        store.add(revenue);

        staff.setText("Nhân Viên");
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });
        store.add(staff);

        jMenuBar1.add(store);

        statistic.setText("Thống Kê");
        statistic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticActionPerformed(evt);
            }
        });

        detail.setText("Chi Tiết");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });
        statistic.add(detail);

        jMenuBar1.add(statistic);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        JOptionPane.showMessageDialog(null, "Phiên Bản 1.0.0.0");
    }//GEN-LAST:event_aboutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        formSanPham sanpham = new formSanPham();
        sanpham.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_productActionPerformed

    private void createBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBillActionPerformed
        formLapHoaDon laphoadon = new formLapHoaDon();
        laphoadon.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createBillActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        formKhachHang khachhang = new formKhachHang();
        khachhang.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_customerActionPerformed

    private void searchBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBillActionPerformed
        formTraCuuHoaDon tracuuhoadon = new formTraCuuHoaDon();
        tracuuhoadon.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_searchBillActionPerformed

    private void revenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueActionPerformed
        formDoanhThu doanhthu = new formDoanhThu();
        doanhthu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_revenueActionPerformed

    private void staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffActionPerformed
        formNhanVien nhanvien = new formNhanVien();
        nhanvien.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_staffActionPerformed

    private void statisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticActionPerformed
        formThongKe thongke = new formThongKe();
        thongke.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_statisticActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        formLogIn login = new formLogIn();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        formThongKe thongke = new formThongKe();
        thongke.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_detailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem createBill;
    private javax.swing.JMenuItem customer;
    private javax.swing.JMenuItem detail;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu function;
    private javax.swing.JLabel image;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem product;
    private javax.swing.JMenuItem revenue;
    private javax.swing.JMenu search;
    private javax.swing.JMenuItem searchBill;
    private javax.swing.JMenuItem staff;
    private javax.swing.JMenu statistic;
    private javax.swing.JMenu store;
    private javax.swing.JMenu system;
    // End of variables declaration//GEN-END:variables
}