/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerpartsstoremanagement;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hamvu
 */
public class formResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form formResetPassword
     */
    public formResetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        lblUserPassword = new javax.swing.JLabel();
        txtUserPassword = new javax.swing.JPasswordField();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Khôi Phục Mật Khẩu");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Khôi Phục Mật Khẩu");

        lblUserID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserID.setText("Tên Đăng Nhập:");

        txtUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                txtUserIDKeyPressed(evt);
            }
        });

        lblUserPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserPassword.setText("Mật Khẩu mới:");

        txtUserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                txtUserPasswordKeyPressed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setText("Khôi phục");
        btnReset.setToolTipText("");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("Trở về");
        btnBack.setToolTipText("");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUserID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack)
                                .addGap(0, 98, Short.MAX_VALUE))
                            .addComponent(txtUserID)
                            .addComponent(txtUserPassword))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnBack))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            String url = ConnectionString.getUrl();
            Connection cnn = DriverManager.getConnection(url);
            String sql = "UPDATE DangNhap SET userpassword = ? WHERE userid = ?";
            PreparedStatement pst = cnn.prepareStatement(sql);
            pst.setString(1, txtUserPassword.getText());
            pst.setString(2, txtUserID.getText());
            
            pst.executeUpdate();           
            JOptionPane.showMessageDialog(null, "Khôi phục mật khẩu thành công!");                        
            cnn.close();
        }
        catch(SQLException sqlex){
            JOptionPane.showMessageDialog(null, sqlex);
        }                 
    }//GEN-LAST:event_btnResetActionPerformed
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        formLogIn login = new formLogIn();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUserIDKeyPressed(KeyEvent evt) {//GEN-FIRST:event_txtUserIDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtUserID.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Yêu cầu nhập tên đăng nhập");
            }
            else if(txtUserPassword.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Yêu cầu nhập mật khẩu");
            }
            else {
                try {
                    String url = ConnectionString.getUrl();
                    Connection cnn = DriverManager.getConnection(url);
                    String sql = "UPDATE DangNhap SET userpassword = ? WHERE userid = ?";
                    PreparedStatement pst = cnn.prepareStatement(sql);
                    pst.setString(1, txtUserPassword.getText());
                    pst.setString(2, txtUserID.getText());
            
                    pst.executeUpdate();           
                    JOptionPane.showMessageDialog(null, "Khôi phục mật khẩu thành công!");                        
                    cnn.close();
                }
                catch(SQLException sqlex){
                    JOptionPane.showMessageDialog(null, sqlex);
                } 
            }
        }
    }//GEN-LAST:event_txtUserIDKeyPressed

    private void txtUserPasswordKeyPressed(KeyEvent evt) {//GEN-FIRST:event_txtUserPasswordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txtUserID.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Yêu cầu nhập tên đăng nhập");
            }
            else if(txtUserPassword.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Yêu cầu nhập mật khẩu");
            }
            else {
                try {
                    String url = ConnectionString.getUrl();
                    Connection cnn = DriverManager.getConnection(url);
                    String sql = "UPDATE DangNhap SET userpassword = ? WHERE userid = ?";
                    PreparedStatement pst = cnn.prepareStatement(sql);
                    pst.setString(1, txtUserPassword.getText());
                    pst.setString(2, txtUserID.getText());
            
                    pst.executeUpdate();           
                    JOptionPane.showMessageDialog(null, "Khôi phục mật khẩu thành công!");                        
                    cnn.close();
                }
                catch(SQLException sqlex){
                    JOptionPane.showMessageDialog(null, sqlex);
                } 
            }
        }
    }//GEN-LAST:event_txtUserPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserPassword;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
